[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/demo"
  to = "/demo.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
  X-Frame-Options = "SAMEORIGIN"
