- intent: ga4.sessions_daily
  patterns:
    - "traffic trend"
  tool: ga4.sessions_daily
  defaults:
    range: last_28_days
- intent: shopify.revenue_summary
  patterns: ["revenue last *", "sales summary", "orders last *", "how much did we sell", "aov last *"]
  tool: shopify.revenue_summary
  defaults: {brand: "labessentials", range: "last_30_days"}
- intent: clarity.hotspots
  patterns: ["clarity hotspots", "top pages issues", "where do users rage click", "hot pages last *", "clarity summary"]
  tool: clarity.hotspots
  defaults: {brand: "labessentials", range: "last_7_days"}
- intent: summary.wow
  patterns: ["week over week", "wow summary", "compare last week", "weekly comparison", "how did we do vs last week"]
  tool: summary.wow
  defaults: {brand: "labessentials", metric: "sessions", window: "7"}
- intent: default
  patterns:
    - "*"
  tool: ga4.sessions_daily