name: Daily Revenue Endpoint Check

on:
  schedule:
    - cron: "15 10 * * *"   # daily at 10:15 UTC
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run revenue smoke test
        run: |
          chmod +x scripts/smoke_revenue_both.sh
          ./scripts/smoke_revenue_both.sh